[[rules]]
id = "generic-secret"
description = "Generic Secret"
regex = '''(?i)(key|secret|token|password)\s*[:=]\s*["']?[A-Za-z0-9+/=_-]{12,}["']?'''
tags = ["key", "token", "secret"]

[allowlist]
description = "Ignore .env files"
paths = [
  '''\.env$'''
]
